save_dir: workspace/resnet

model:
  backbone:
    name: CustomCspNet
    net_cfg: [[ 'Conv', 3, 32, 3, 2],  # 1/2
              [ 'MaxPool', 3, 2 ],  # 1/4
              [ 'CspBlock', 32, 1, 3, 1 ],  # 1/4
              [ 'CspBlock', 64, 2, 3, 2 ],  # 1/8
              [ 'CspBlock', 128, 2, 3, 2 ],  # 1/16
              [ 'CspBlock', 256, 3, 3, 2 ]]  # 1/32
